# Generated by Django 5.2.5 on 2025-08-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="topic",
            field=models.CharField(db_index=True, default="general", max_length=100),
        ),
    ]
