# Generated by Django 5.2.5 on 2025-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("message", "0002_article_topic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="topic",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
